[[pages]]
path = "STR/pages/0_accueil.py"
name = "Accueil"
icon = "⚽"

[[pages]]
path = "STR/pages/2_ideal.py"
name = "Trouver le joueur idéal"
icon = "🔎"

[[pages]]
path = "STR/pages/1_similarite.py"
name = "Recherche d'un joueur similaire"
icon = "👬🏻"


